# Generated by Django 5.2.4 on 2025-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
